# Form implementation generated from reading ui file 'Final.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(941, 631)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 941, 631))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffff,\n"
"        stop:0.4 #cbf7ff,\n"
"        stop:1 #a6ecf7\n"
"    );\n"
"}")
        self.widget.setObjectName("widget")
        self.mainwidget = QtWidgets.QWidget(parent=self.widget)
        self.mainwidget.setEnabled(True)
        self.mainwidget.setGeometry(QtCore.QRect(0, 0, 941, 631))
        self.mainwidget.setStyleSheet("#label_phrase{\n"
"    font-family: \"Open Sans Light\";\n"
"    font-size: 12pt;\n"
"    font-weight: 300;\n"
"    color: #002B5B;\n"
"    border: none;              /* removes the border completely */\n"
"    background: transparent;   /* ensures no background box */\n"
"}\n"
"")
        self.mainwidget.setObjectName("mainwidget")
        self.label_smalllogo = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_smalllogo.setGeometry(QtCore.QRect(10, 0, 51, 61))
        self.label_smalllogo.setStyleSheet("#label_smalllogo{\n"
"background-color:#031b3d;\n"
"}\n"
"\n"
"#label_smalllogo{\n"
"border-image: url(\"C:/Users/Missy/Downloads/ENTREPREDICT_Icon_Option_1_-_Circuit-Graph_E-removebg-preview.png\");\n"
"}")
        self.label_smalllogo.setText("")
        self.label_smalllogo.setObjectName("label_smalllogo")
        self.label_upperhome = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_upperhome.setGeometry(QtCore.QRect(0, 0, 941, 61))
        self.label_upperhome.setStyleSheet("#label_upperhome{\n"
"background-color:#031b3d;\n"
"}")
        self.label_upperhome.setText("")
        self.label_upperhome.setObjectName("label_upperhome")
        self.plainTextEdit_Entrep = QtWidgets.QPlainTextEdit(parent=self.mainwidget)
        self.plainTextEdit_Entrep.setEnabled(False)
        self.plainTextEdit_Entrep.setGeometry(QtCore.QRect(70, 20, 191, 41))
        self.plainTextEdit_Entrep.setStyleSheet("#plainTextEdit_Entrep{\n"
" font-family: \"Montserrat ExtraBold\";\n"
"    font-size: 16pt;\n"
"font-weight: 600;\n"
"color:white;\n"
"background-color:#031b3d;\n"
"border:none;\n"
"}")
        self.plainTextEdit_Entrep.setObjectName("plainTextEdit_Entrep")
        self.frame_sidebar = QtWidgets.QFrame(parent=self.mainwidget)
        self.frame_sidebar.setGeometry(QtCore.QRect(10, 70, 161, 541))
        self.frame_sidebar.setStyleSheet("#frame_sidebar {\n"
"    background-color: #002B5B;\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_sidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_sidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.homePushButton = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.homePushButton.setGeometry(QtCore.QRect(40, 30, 91, 31))
        self.homePushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.homePushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.homePushButton.setObjectName("homePushButton")
        self.inventoryPushButton = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.inventoryPushButton.setGeometry(QtCore.QRect(40, 80, 91, 31))
        self.inventoryPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.inventoryPushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.inventoryPushButton.setObjectName("inventoryPushButton")
        self.salesPushButton = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.salesPushButton.setGeometry(QtCore.QRect(40, 130, 91, 31))
        self.salesPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.salesPushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.salesPushButton.setObjectName("salesPushButton")
        self.predictionPushButton = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.predictionPushButton.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.predictionPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.predictionPushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"\n"
"")
        self.predictionPushButton.setObjectName("predictionPushButton")
        self.incomePushButton = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.incomePushButton.setGeometry(QtCore.QRect(40, 230, 91, 31))
        self.incomePushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.incomePushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.incomePushButton.setObjectName("incomePushButton")
        self.logOutPushButton = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.logOutPushButton.setGeometry(QtCore.QRect(40, 480, 91, 31))
        self.logOutPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logOutPushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 6px 18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.logOutPushButton.setObjectName("logOutPushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 80, 701, 531))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.UpArrowCursor))
        self.stackedWidget.setStyleSheet("background : transparent")
        self.stackedWidget.setObjectName("stackedWidget")
        self.inventory_widget = QtWidgets.QWidget()
        self.inventory_widget.setObjectName("inventory_widget")
        self.widget_inventory = QtWidgets.QWidget(parent=self.inventory_widget)
        self.widget_inventory.setGeometry(QtCore.QRect(10, 10, 671, 481))
        self.widget_inventory.setStyleSheet("#widget_inventory {\n"
"    background: rgba(255, 255, 255, 0.15);     /* semi-transparent glass effect */\n"
"    border: 2px solid #031b3d;                 /* navy border */\n"
"    border-radius: 15px;                       /* smoother corners */\n"
"    backdrop-filter: blur(10px);               /* subtle blur for depth */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.widget_inventory.setObjectName("widget_inventory")
        self.label_inventory = QtWidgets.QLabel(parent=self.widget_inventory)
        self.label_inventory.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.label_inventory.setStyleSheet("#label_inventory {\n"
"    color: #031b3d;                  /* Deep navy text for contrast */\n"
"    font-weight: 900;                /* Bold emphasis */\n"
"    font-size: 22px;                 /* Slightly larger title */\n"
"    background: transparent;         /* Keep background clean */\n"
"    letter-spacing: 1px;             /* Space out letters slightly */\n"
"    text-transform: uppercase;       /* Make “Inventory” more assertive */\n"
"    border: none;                    /* Remove any frame borders */\n"
"    \n"
"    /* Subtle cyan glow for elegance */\n"
"    text-shadow: 0px 0px 6px #00ffff;\n"
"}")
        self.label_inventory.setObjectName("label_inventory")
        self.label_search = QtWidgets.QLabel(parent=self.widget_inventory)
        self.label_search.setGeometry(QtCore.QRect(410, 60, 61, 31))
        self.label_search.setStyleSheet("#label_search {\n"
"    color: #031b3d;            /* Same navy tone for consistency */\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding-right: 5px;        /* Adds spacing between label and input */\n"
"}\n"
"")
        self.label_search.setObjectName("label_search")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.widget_inventory)
        self.lineEdit_search.setGeometry(QtCore.QRect(480, 60, 151, 31))
        self.lineEdit_search.setStyleSheet("#lineEdit_search {\n"
"    background: rgba(255, 255, 255, 70);  /* Semi-transparent white */\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    color: #031b3d;\n"
"    font-size: 14px;\n"
"    selection-background-color: #00ffff;  /* Cyan highlight when selecting text */\n"
"    selection-color: #031b3d;\n"
"}\n"
"\n"
"#lineEdit_search:focus {\n"
"    border: 2px solid #00ffff;            /* Cyan glow on focus */\n"
"    background: rgba(255, 255, 255, 90);\n"
"}")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.addbutton = QtWidgets.QPushButton(parent=self.widget_inventory)
        self.addbutton.setGeometry(QtCore.QRect(30, 120, 91, 31))
        self.addbutton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addbutton.setStyleSheet("#addbutton {\n"
"    background-color: #002B5B;    /* Very light cyan tint */\n"
"    border: 2px solid #031b3d;                  /* Deep navy border */\n"
"    border-radius: 9px;\n"
"    color: #FFFFFF;\n"
"    font-weight: 500;\n"
"    font-size: 11px;                            /* Smaller text */\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#addbutton:hover {\n"
"    background-color: rgba(0, 255, 255, 60);    /* Subtle cyan highlight */\n"
"    border: 2px solid #00ffff;                  /* Cyan glow */\n"
"}\n"
"\n"
"#addbutton:pressed {\n"
"    background-color: rgba(0, 255, 255, 90);    /* Slightly stronger color */\n"
"}\n"
"")
        self.addbutton.setObjectName("addbutton")
        self.deletebutton = QtWidgets.QPushButton(parent=self.widget_inventory)
        self.deletebutton.setGeometry(QtCore.QRect(130, 120, 101, 31))
        self.deletebutton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.deletebutton.setStyleSheet("#deletebutton {\n"
"    background-color: #002B5B;    /* Soft coral tint (less aggressive than red) */\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    font-weight: 500;\n"
"    font-size: 11px;                            /* Smaller text */\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#deletebutton:hover {\n"
"    background-color: rgba(255, 99, 71, 60);    /* Gentle coral hover */\n"
"    border: 2px solid #00ffff;                  /* Cyan hover border for harmony */\n"
"}\n"
"\n"
"#deletebutton:pressed {\n"
"    background-color: rgba(255, 99, 71, 90);\n"
"}")
        self.deletebutton.setObjectName("deletebutton")
        self.table_inventory = QtWidgets.QTableView(parent=self.widget_inventory)
        self.table_inventory.setGeometry(QtCore.QRect(30, 160, 611, 291))
        self.table_inventory.setObjectName("table_inventory")
        self.stackedWidget.addWidget(self.inventory_widget)
        self.home_widget = QtWidgets.QWidget()
        self.home_widget.setObjectName("home_widget")
        self.label_welcome = QtWidgets.QLabel(parent=self.home_widget)
        self.label_welcome.setGeometry(QtCore.QRect(30, 20, 271, 41))
        self.label_welcome.setStyleSheet("#label_welcome {\n"
"    color: #00E5FF;\n"
"    font-family: \"Poppins ExtraBold\";\n"
"    font-size: 34pt;\n"
"    font-weight: 800;\n"
"    letter-spacing: 2px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-shadow: 0px 0px 10px rgba(0, 229, 255, 0.6);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.label_welcome.setObjectName("label_welcome")
        self.label_summary = QtWidgets.QLabel(parent=self.home_widget)
        self.label_summary.setGeometry(QtCore.QRect(40, 70, 301, 31))
        self.label_summary.setStyleSheet("#label_summary {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #002B5B; /* Black text */\n"
"    background-color: transparent; /* Transparent background */\n"
"}\n"
"")
        self.label_summary.setObjectName("label_summary")
        self.frame_status = QtWidgets.QFrame(parent=self.home_widget)
        self.frame_status.setGeometry(QtCore.QRect(30, 120, 581, 191))
        self.frame_status.setStyleSheet("#frame_status {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(224, 247, 250, 255),  /* light cyan */\n"
"        stop:1 rgba(255, 255, 255, 255)   /* soft white */\n"
"    );\n"
"    border-radius: 20px;\n"
"    border: 1px solid rgba(0, 188, 212, 60); /* subtle cyan border */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.frame_status.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_status.setObjectName("frame_status")
        self.label_status = QtWidgets.QLabel(parent=self.frame_status)
        self.label_status.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.label_status.setStyleSheet("#label_status{\n"
"    background-color: transparent;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 13pt;\n"
"    font-weight: 600;\n"
"    color: #000000;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.label_status.setObjectName("label_status")
        self.label_predicted = QtWidgets.QLabel(parent=self.frame_status)
        self.label_predicted.setGeometry(QtCore.QRect(40, 40, 491, 51))
        self.label_predicted.setStyleSheet("#label_predicted {\n"
"    font-size: 36pt;      /* Adjust bigger or smaller depending on your layout */\n"
"    font-weight: bold;\n"
"    color: #002B5B;       /* Replace with the exact color of your sidebar frame */\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_predicted.setObjectName("label_predicted")
        self.label_confidence = QtWidgets.QLabel(parent=self.frame_status)
        self.label_confidence.setGeometry(QtCore.QRect(50, 100, 271, 31))
        self.label_confidence.setStyleSheet("#label_confidence {\n"
"    font-size: 15pt;      /* Smaller than 36pt of PREDICTED SUCCESS */\n"
"    font-weight: semi-bold;\n"
"    color: #002B5B;       /* Same as sidebar / PREDICTED SUCCESS for consistency */\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_confidence.setObjectName("label_confidence")
        self.label_last = QtWidgets.QLabel(parent=self.frame_status)
        self.label_last.setGeometry(QtCore.QRect(50, 140, 231, 21))
        self.label_last.setStyleSheet("#label_last {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #002B5B; /* Black text */\n"
"    background-color: transparent; /* Transparent background */\n"
"}\n"
"")
        self.label_last.setObjectName("label_last")
        self.frame_tips = QtWidgets.QFrame(parent=self.home_widget)
        self.frame_tips.setGeometry(QtCore.QRect(30, 320, 301, 191))
        self.frame_tips.setStyleSheet("#frame_tips {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(224, 247, 250, 255),  /* light cyan */\n"
"        stop:1 rgba(255, 255, 255, 255)   /* soft white */\n"
"    );\n"
"    border-radius: 20px;\n"
"    border: 1px solid rgba(0, 188, 212, 60); /* subtle cyan border */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.frame_tips.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tips.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tips.setObjectName("frame_tips")
        self.label_tips = QtWidgets.QLabel(parent=self.frame_tips)
        self.label_tips.setGeometry(QtCore.QRect(8, 19, 191, 31))
        self.label_tips.setStyleSheet("#label_tips{\n"
"    background-color: transparent;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 13pt;\n"
"    font-weight: 600;\n"
"    color: #000000;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.label_tips.setObjectName("label_tips")
        self.label_bullet = QtWidgets.QLabel(parent=self.frame_tips)
        self.label_bullet.setGeometry(QtCore.QRect(20, 70, 261, 71))
        self.label_bullet.setStyleSheet("#label_bullet{\n"
"    font-size: 11pt;          /* Similar to summary/last update */\n"
"    font-weight: normal;       /* Keep it readable */\n"
"    color: #001F3F;            /* Consistent text color */\n"
"    background: transparent;\n"
"    border: none;              /* No border */\n"
"}\n"
"")
        self.label_bullet.setObjectName("label_bullet")
        self.label_username = QtWidgets.QLabel(parent=self.home_widget)
        self.label_username.setGeometry(QtCore.QRect(270, 30, 151, 31))
        self.label_username.setStyleSheet("#label_username {\n"
"    color: #00B8D4;  /* deeper cyan-blue for better contrast */\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    font-weight: 500;\n"
"    letter-spacing: 0.5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.label_username.setObjectName("label_username")
        self.stackedWidget.addWidget(self.home_widget)
        self.prediction_widget = QtWidgets.QWidget()
        self.prediction_widget.setObjectName("prediction_widget")
        self.widget_inventory_3 = QtWidgets.QWidget(parent=self.prediction_widget)
        self.widget_inventory_3.setGeometry(QtCore.QRect(10, 10, 671, 481))
        self.widget_inventory_3.setStyleSheet("#widget_inventory_3 {\n"
"    background: rgba(255, 255, 255, 0.15);     /* semi-transparent glass effect */\n"
"    border: 2px solid #031b3d;                 /* navy border */\n"
"    border-radius: 15px;                       /* smoother corners */\n"
"    backdrop-filter: blur(10px);               /* subtle blur for depth */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.widget_inventory_3.setObjectName("widget_inventory_3")
        self.label_inventory_3 = QtWidgets.QLabel(parent=self.widget_inventory_3)
        self.label_inventory_3.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.label_inventory_3.setStyleSheet("#label_inventory_3 {\n"
"    color: #031b3d;                  /* Deep navy text for contrast */\n"
"    font-weight: 900;                /* Bold emphasis */\n"
"    font-size: 22px;                 /* Slightly larger title */\n"
"    background: transparent;         /* Keep background clean */\n"
"    letter-spacing: 1px;             /* Space out letters slightly */\n"
"    text-transform: uppercase;       /* Make “Inventory” more assertive */\n"
"    border: none;                    /* Remove any frame borders */\n"
"    \n"
"    /* Subtle cyan glow for elegance */\n"
"    text-shadow: 0px 0px 6px #00ffff;\n"
"}")
        self.label_inventory_3.setObjectName("label_inventory_3")
        self.plainTextEdit_prediction = QtWidgets.QPlainTextEdit(parent=self.widget_inventory_3)
        self.plainTextEdit_prediction.setGeometry(QtCore.QRect(20, 60, 351, 51))
        self.plainTextEdit_prediction.setStyleSheet("#plainTextEdit_prediction {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #002B5B; /* Black text */\n"
"    background-color: transparent; /* Transparent background */\n"
"    border:none;\n"
"}\n"
"")
        self.plainTextEdit_prediction.setObjectName("plainTextEdit_prediction")
        self.frame = QtWidgets.QFrame(parent=self.widget_inventory_3)
        self.frame.setGeometry(QtCore.QRect(30, 120, 291, 331))
        self.frame.setStyleSheet("#frame {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c8f1ff, stop:1 #e2fbff);\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.netIncomeQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.netIncomeQLine.setGeometry(QtCore.QRect(160, 50, 111, 31))
        self.netIncomeQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.netIncomeQLine.setObjectName("netIncomeQLine")
        self.label_totalliabilities = QtWidgets.QLabel(parent=self.frame)
        self.label_totalliabilities.setGeometry(QtCore.QRect(10, 90, 111, 21))
        self.label_totalliabilities.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_totalliabilities.setObjectName("label_totalliabilities")
        self.totalAssetsQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.totalAssetsQLine.setGeometry(QtCore.QRect(20, 50, 111, 31))
        self.totalAssetsQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.totalAssetsQLine.setObjectName("totalAssetsQLine")
        self.label_equity = QtWidgets.QLabel(parent=self.frame)
        self.label_equity.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.label_equity.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_equity.setObjectName("label_equity")
        self.operatingIncomeQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.operatingIncomeQLine.setGeometry(QtCore.QRect(160, 110, 111, 31))
        self.operatingIncomeQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.operatingIncomeQLine.setObjectName("operatingIncomeQLine")
        self.totalEquityQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.totalEquityQLine.setGeometry(QtCore.QRect(20, 170, 113, 31))
        self.totalEquityQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.totalEquityQLine.setObjectName("totalEquityQLine")
        self.label_totalassets = QtWidgets.QLabel(parent=self.frame)
        self.label_totalassets.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label_totalassets.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_totalassets.setObjectName("label_totalassets")
        self.label_net = QtWidgets.QLabel(parent=self.frame)
        self.label_net.setGeometry(QtCore.QRect(150, 30, 91, 21))
        self.label_net.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_net.setObjectName("label_net")
        self.label_currentliabilities = QtWidgets.QLabel(parent=self.frame)
        self.label_currentliabilities.setGeometry(QtCore.QRect(10, 210, 121, 21))
        self.label_currentliabilities.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_currentliabilities.setObjectName("label_currentliabilities")
        self.label_operating = QtWidgets.QLabel(parent=self.frame)
        self.label_operating.setGeometry(QtCore.QRect(150, 90, 131, 21))
        self.label_operating.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_operating.setObjectName("label_operating")
        self.totalLiabilitiesQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.totalLiabilitiesQLine.setGeometry(QtCore.QRect(20, 110, 111, 31))
        self.totalLiabilitiesQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.totalLiabilitiesQLine.setObjectName("totalLiabilitiesQLine")
        self.currentAssetsQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.currentAssetsQLine.setGeometry(QtCore.QRect(160, 170, 113, 31))
        self.currentAssetsQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.currentAssetsQLine.setObjectName("currentAssetsQLine")
        self.currentLiabilitiesQLine = QtWidgets.QLineEdit(parent=self.frame)
        self.currentLiabilitiesQLine.setGeometry(QtCore.QRect(20, 230, 111, 31))
        self.currentLiabilitiesQLine.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #1c3f63;\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00b4d8;\n"
"    background-color: #f0faff;\n"
"    box-shadow: 0 0 6px rgba(0, 180, 216, 0.3);\n"
"}\n"
"")
        self.currentLiabilitiesQLine.setObjectName("currentLiabilitiesQLine")
        self.label_currentassets = QtWidgets.QLabel(parent=self.frame)
        self.label_currentassets.setGeometry(QtCore.QRect(150, 150, 111, 21))
        self.label_currentassets.setStyleSheet("QLabel {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    color: #0a1f33;\n"
"    font-family: \"Segoe UI Black\";\n"
"    font-size: 24px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#subtitle_label {\n"
"    color: #1a3e57;\n"
"    font-family: \"Segoe UI\";\n"
"    font-style: italic;\n"
"    font-size: 13px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"}\n"
"")
        self.label_currentassets.setObjectName("label_currentassets")
        self.predictButton = QtWidgets.QPushButton(parent=self.frame)
        self.predictButton.setGeometry(QtCore.QRect(100, 280, 91, 31))
        self.predictButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.predictButton.setStyleSheet("#donebutton {\n"
"    background-color: #002B5B;    /* Very light cyan tint */\n"
"    border: 2px solid #031b3d;                  /* Deep navy border */\n"
"    border-radius: 9px;\n"
"    color: #FFFFFF;\n"
"    font-weight: 500;\n"
"    font-size: 11px;                            /* Smaller text */\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#donebutton:hover {\n"
"    background-color: rgba(0, 255, 255, 60);    /* Subtle cyan highlight */\n"
"    border: 2px solid #00ffff;                  /* Cyan glow */\n"
"}\n"
"\n"
"#donebutton:pressed {\n"
"    background-color: rgba(0, 255, 255, 90);    /* Slightly stronger color */\n"
"}\n"
"")
        self.predictButton.setObjectName("predictButton")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_inventory_3)
        self.frame_2.setGeometry(QtCore.QRect(350, 190, 291, 171))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c8f1ff, stop:1 #e2fbff);\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.result_label = QtWidgets.QLabel(parent=self.frame_2)
        self.result_label.setGeometry(QtCore.QRect(20, 10, 151, 51))
        self.result_label.setStyleSheet("#result_label {\n"
"                  \n"
"    font-weight: 900;                /* Bold emphasis */\n"
"    font-size: 22px;                 /* Slightly larger title */\n"
"    background: transparent;         /* Keep background clean */\n"
"    letter-spacing: 2px;             /* Space out letters slightly */\n"
"    text-transform: uppercase;       /* Make “Inventory” more assertive */\n"
"    border: none;                    /* Remove any frame borders */\n"
"    \n"
"    /* Subtle cyan glow for elegance */\n"
"    text-shadow: 0px 0px 6px #00ffff;\n"
"}")
        self.result_label.setObjectName("result_label")
        self.percentage_label = QtWidgets.QLabel(parent=self.frame_2)
        self.percentage_label.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.percentage_label.setStyleSheet("#percentage_label{\n"
"                  \n"
"    font-weight: 900;                /* Bold emphasis */\n"
"    font-size: 20px;                 /* Slightly larger title */\n"
"    background: transparent;         /* Keep background clean */\n"
"               /* Space out letters slightly */\n"
"    text-transform: uppercase;       /* Make “Inventory” more assertive */\n"
"    border: none;                    /* Remove any frame borders */\n"
"    \n"
"    /* Subtle cyan glow for elegance */\n"
"    text-shadow: 0px 0px 6px #00ffff;\n"
"}")
        self.percentage_label.setText("")
        self.percentage_label.setObjectName("percentage_label")
        self.message_label = QtWidgets.QLabel(parent=self.frame_2)
        self.message_label.setGeometry(QtCore.QRect(20, 100, 241, 51))
        self.message_label.setStyleSheet("background: transparent;\n"
" font-weight: 900; ")
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.stackedWidget.addWidget(self.prediction_widget)
        self.income_widget = QtWidgets.QWidget()
        self.income_widget.setObjectName("income_widget")
        self.stackedWidget.addWidget(self.income_widget)
        self.sales_widget = QtWidgets.QWidget()
        self.sales_widget.setObjectName("sales_widget")
        self.widget_inventory_2 = QtWidgets.QWidget(parent=self.sales_widget)
        self.widget_inventory_2.setGeometry(QtCore.QRect(10, 10, 671, 491))
        self.widget_inventory_2.setStyleSheet("#widget_inventory_2 {\n"
"    background: rgba(255, 255, 255, 0.15);     /* semi-transparent glass effect */\n"
"    border: 2px solid #031b3d;                 /* navy border */\n"
"    border-radius: 15px;                       /* smoother corners */\n"
"    backdrop-filter: blur(10px);               /* subtle blur for depth */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.widget_inventory_2.setObjectName("widget_inventory_2")
        self.label_inventory_2 = QtWidgets.QLabel(parent=self.widget_inventory_2)
        self.label_inventory_2.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.label_inventory_2.setStyleSheet("#label_inventory_2 {\n"
"    color: #031b3d;                  /* Deep navy text for contrast */\n"
"    font-weight: 900;                /* Bold emphasis */\n"
"    font-size: 22px;                 /* Slightly larger title */\n"
"    background: transparent;         /* Keep background clean */\n"
"    letter-spacing: 1px;             /* Space out letters slightly */\n"
"    text-transform: uppercase;       /* Make “Inventory” more assertive */\n"
"    border: none;                    /* Remove any frame borders */\n"
"    \n"
"    /* Subtle cyan glow for elegance */\n"
"    text-shadow: 0px 0px 6px #00ffff;\n"
"}")
        self.label_inventory_2.setObjectName("label_inventory_2")
        self.label_search_2 = QtWidgets.QLabel(parent=self.widget_inventory_2)
        self.label_search_2.setGeometry(QtCore.QRect(360, 60, 61, 31))
        self.label_search_2.setStyleSheet("#label_search_2 {\n"
"    color: #031b3d;            /* Same navy tone for consistency */\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding-right: 5px;        /* Adds spacing between label and input */\n"
"}\n"
"")
        self.label_search_2.setObjectName("label_search_2")
        self.lineEdit_search_2 = QtWidgets.QLineEdit(parent=self.widget_inventory_2)
        self.lineEdit_search_2.setGeometry(QtCore.QRect(420, 60, 151, 31))
        self.lineEdit_search_2.setStyleSheet("#lineEdit_search_2 {\n"
"    background: rgba(255, 255, 255, 70);  /* Semi-transparent white */\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    color: #031b3d;\n"
"    font-size: 14px;\n"
"    selection-background-color: #00ffff;  /* Cyan highlight when selecting text */\n"
"    selection-color: #031b3d;\n"
"}\n"
"\n"
"#lineEdit_search:focus {\n"
"    border: 2px solid #00ffff;            /* Cyan glow on focus */\n"
"    background: rgba(255, 255, 255, 90);\n"
"}")
        self.lineEdit_search_2.setObjectName("lineEdit_search_2")
        self.frame_total = QtWidgets.QFrame(parent=self.widget_inventory_2)
        self.frame_total.setGeometry(QtCore.QRect(50, 110, 151, 80))
        self.frame_total.setStyleSheet("#frame_total {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c8f1ff, stop:1 #e2fbff);\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}")
        self.frame_total.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_total.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_total.setObjectName("frame_total")
        self.label_title = QtWidgets.QLabel(parent=self.frame_total)
        self.label_title.setGeometry(QtCore.QRect(50, 10, 61, 20))
        self.label_title.setStyleSheet("#label_title {\n"
"    color: #031b3d;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    background-color:transparent;\n"
"}")
        self.label_title.setObjectName("label_title")
        self.label_text = QtWidgets.QLabel(parent=self.frame_total)
        self.label_text.setGeometry(QtCore.QRect(60, 40, 51, 16))
        self.label_text.setStyleSheet("#label_text {\n"
"    color: #031b3d;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"    background-color: transparent;\n"
"}")
        self.label_text.setObjectName("label_text")
        self.frame_revenue = QtWidgets.QFrame(parent=self.widget_inventory_2)
        self.frame_revenue.setGeometry(QtCore.QRect(250, 110, 151, 80))
        self.frame_revenue.setStyleSheet("#frame_revenue {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c8f1ff, stop:1 #e2fbff);\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}")
        self.frame_revenue.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_revenue.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_revenue.setObjectName("frame_revenue")
        self.label_revenue = QtWidgets.QLabel(parent=self.frame_revenue)
        self.label_revenue.setGeometry(QtCore.QRect(50, 10, 49, 16))
        self.label_revenue.setStyleSheet("#label_revenue {\n"
"    color: #031b3d;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    background-color:transparent;\n"
"}")
        self.label_revenue.setObjectName("label_revenue")
        self.label_amount = QtWidgets.QLabel(parent=self.frame_revenue)
        self.label_amount.setGeometry(QtCore.QRect(40, 40, 81, 20))
        self.label_amount.setStyleSheet("#label_amount {\n"
"    color: #031b3d;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"    background-color: transparent;\n"
"}")
        self.label_amount.setObjectName("label_amount")
        self.frame_top = QtWidgets.QFrame(parent=self.widget_inventory_2)
        self.frame_top.setGeometry(QtCore.QRect(450, 110, 151, 80))
        self.frame_top.setStyleSheet("#frame_top {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c8f1ff, stop:1 #e2fbff);\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_top = QtWidgets.QLabel(parent=self.frame_top)
        self.label_top.setGeometry(QtCore.QRect(40, 10, 71, 20))
        self.label_top.setStyleSheet("#label_top {\n"
"    color: #031b3d;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    background-color:transparent;\n"
"}")
        self.label_top.setObjectName("label_top")
        self.label_product = QtWidgets.QLabel(parent=self.frame_top)
        self.label_product.setGeometry(QtCore.QRect(30, 40, 101, 20))
        self.label_product.setStyleSheet("#label_product {\n"
"    color: #031b3d;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"    background-color: transparent;\n"
"}")
        self.label_product.setObjectName("label_product")
        self.frame_monthly = QtWidgets.QFrame(parent=self.widget_inventory_2)
        self.frame_monthly.setGeometry(QtCore.QRect(50, 210, 551, 211))
        self.frame_monthly.setStyleSheet("#frame_monthly {\n"
"    background-color: rgba(255, 255, 255, 0.6);\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 15px;\n"
"    padding: 12px;\n"
"}\n"
"")
        self.frame_monthly.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_monthly.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_monthly.setObjectName("frame_monthly")
        self.label_monthly = QtWidgets.QLabel(parent=self.frame_monthly)
        self.label_monthly.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.label_monthly.setStyleSheet("#label_monthly {\n"
"    color: #031b3d;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    background-color: transparent;\n"
"    border-radius: 6px;\n"
"    padding: 3px 6px;\n"
"}\n"
"")
        self.label_monthly.setObjectName("label_monthly")
        self.label_month = QtWidgets.QLabel(parent=self.widget_inventory_2)
        self.label_month.setGeometry(QtCore.QRect(50, 60, 61, 41))
        self.label_month.setStyleSheet("#label_month {\n"
"    color: #031b3d;            /* Same navy tone for consistency */\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding-right: 5px;        /* Adds spacing between label and input */\n"
"}\n"
"")
        self.label_month.setObjectName("label_month")
        self.label_month1 = QtWidgets.QLabel(parent=self.widget_inventory_2)
        self.label_month1.setGeometry(QtCore.QRect(120, 60, 131, 31))
        self.label_month1.setStyleSheet("#label_month1 {\n"
"    background: rgba(255, 255, 255, 70);  /* Semi-transparent white */\n"
"    border: 2px solid #031b3d;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    color: #031b3d;\n"
"    font-size: 14px;\n"
"    selection-background-color: #00ffff;  /* Cyan highlight when selecting text */\n"
"    selection-color: #031b3d;\n"
"}\n"
"\n"
"#label_month1:focus {\n"
"    border: 2px solid #00ffff;            /* Cyan glow on focus */\n"
"    background: rgba(255, 255, 255, 90);\n"
"}")
        self.label_month1.setObjectName("label_month1")
        self.stackedWidget.addWidget(self.sales_widget)
        self.label_upperhome.raise_()
        self.label_smalllogo.raise_()
        self.plainTextEdit_Entrep.raise_()
        self.frame_sidebar.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plainTextEdit_Entrep.setPlainText(_translate("Form", "ENTREPREDICT"))
        self.homePushButton.setText(_translate("Form", "Home"))
        self.inventoryPushButton.setText(_translate("Form", "Inventory"))
        self.salesPushButton.setText(_translate("Form", "Sales"))
        self.predictionPushButton.setText(_translate("Form", "Prediction"))
        self.incomePushButton.setText(_translate("Form", "Income"))
        self.logOutPushButton.setText(_translate("Form", "Log Out"))
        self.label_inventory.setText(_translate("Form", "Inventory"))
        self.label_search.setText(_translate("Form", "Search:"))
        self.lineEdit_search.setPlaceholderText(_translate("Form", "Search"))
        self.addbutton.setText(_translate("Form", "Add Product"))
        self.deletebutton.setText(_translate("Form", "Delete Selected"))
        self.label_welcome.setText(_translate("Form", "Welcome!"))
        self.label_summary.setText(_translate("Form", "Here\'s your business summary."))
        self.label_status.setText(_translate("Form", "Business Status"))
        self.label_predicted.setText(_translate("Form", "PREDICTED SUCCESS!"))
        self.label_confidence.setText(_translate("Form", "Confidence Level: 87%"))
        self.label_last.setText(_translate("Form", "Last Prediction update  10/09/25"))
        self.label_tips.setText(_translate("Form", "Tips for Improvement "))
        self.label_bullet.setText(_translate("Form", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Maintain sales growth</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Reduce slow-moving inventory</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Monitor next month\'s expenses</li></ul></body></html>"))
        self.label_username.setText(_translate("Form", "[USERNAME]"))
        self.label_inventory_3.setText(_translate("Form", "PREDICTION"))
        self.plainTextEdit_prediction.setPlainText(_translate("Form", "Input your financial data to forecast future sales performance."))
        self.label_totalliabilities.setText(_translate("Form", "Total Liabilities:"))
        self.label_equity.setText(_translate("Form", "Total Equity:"))
        self.label_totalassets.setText(_translate("Form", "Total Assets:"))
        self.label_net.setText(_translate("Form", "Net  Income:"))
        self.label_currentliabilities.setText(_translate("Form", "Current Liabilities:"))
        self.label_operating.setText(_translate("Form", "Operating Income:"))
        self.label_currentassets.setText(_translate("Form", "Current Assets:"))
        self.predictButton.setText(_translate("Form", "PREDICT"))
        self.result_label.setText(_translate("Form", "Result"))
        self.label_inventory_2.setText(_translate("Form", "SALES"))
        self.label_search_2.setText(_translate("Form", "Search:"))
        self.lineEdit_search_2.setPlaceholderText(_translate("Form", "Search"))
        self.label_title.setText(_translate("Form", "Total Sales"))
        self.label_text.setText(_translate("Form", "125"))
        self.label_revenue.setText(_translate("Form", "Revenue"))
        self.label_amount.setText(_translate("Form", "125,000"))
        self.label_top.setText(_translate("Form", "Top Product"))
        self.label_product.setText(_translate("Form", "Product X"))
        self.label_monthly.setText(_translate("Form", "Daily Sales"))
        self.label_month.setText(_translate("Form", "Month:"))
        self.label_month1.setText(_translate("Form", "October"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
