# Form implementation generated from reading ui file 'reportPopUp.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(487, 328)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 491, 331))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffff,\n"
"        stop:0.4 #cbf7ff,\n"
"        stop:1 #a6ecf7\n"
"    );\n"
"}")
        self.widget.setObjectName("widget")
        self.reportTableView = QtWidgets.QTableView(parent=self.widget)
        self.reportTableView.setGeometry(QtCore.QRect(45, 41, 411, 231))
        self.reportTableView.setStyleSheet("")
        self.reportTableView.setObjectName("reportTableView")
        self.submitPushButton = QtWidgets.QPushButton(parent=self.widget)
        self.submitPushButton.setGeometry(QtCore.QRect(210, 283, 91, 31))
        self.submitPushButton.setStyleSheet("#submitPushButton {\n"
"    background-color: #002B5B;    /* Very light cyan tint */\n"
"    border: 2px solid #031b3d;                  /* Deep navy border */\n"
"    border-radius: 9px;\n"
"    color: #FFFFFF;\n"
"    font-weight: 500;\n"
"    font-size: 11px;                            /* Smaller text */\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#donebutton:hover {\n"
"    background-color: rgba(0, 255, 255, 60);    /* Subtle cyan highlight */\n"
"    border: 2px solid #00ffff;                  /* Cyan glow */\n"
"}\n"
"\n"
"#donebutton:pressed {\n"
"    background-color: rgba(0, 255, 255, 90);    /* Slightly stronger color */\n"
"}\n"
"")
        self.submitPushButton.setObjectName("submitPushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.submitPushButton.setText(_translate("Form", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
