# Form implementation generated from reading ui file 'tuturialfinal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(958, 651)
        Form.setStyleSheet("#Form{\n"
"    font-family: \"Open Sans Light\";\n"
"    font-size: 12pt;\n"
"    font-weight: 300;\n"
"    color: #002B5B;\n"
"    border: none;              /* removes the border completely */\n"
"    background: transparent;   /* ensures no background box */\n"
"}\n"
"")
        self.labeltur = QtWidgets.QLabel(parent=Form)
        self.labeltur.setGeometry(QtCore.QRect(0, 5, 991, 61))
        self.labeltur.setStyleSheet("#labeltur{\n"
"background-color:#031b3d;\n"
"}")
        self.labeltur.setText("")
        self.labeltur.setObjectName("labeltur")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 10, 61, 51))
        self.label.setStyleSheet("#label{\n"
"background-color:#031b3d;\n"
"}\n"
"\n"
"#label{\n"
"border-image: url(\"C:/Users/USER/Documents/system_90/nagao_backend/ENTREPREDICT_Icon_Option_1_-_Circuit-Graph_E-removebg-preview.png\");\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 241, 41))
        self.label_2.setStyleSheet("#label_2{\n"
" font-family: \"Montserrat ExtraBold\";\n"
"    font-size: 16pt;\n"
"font-weight: 600;\n"
"color:white;\n"
"background-color:#031b3d;\n"
"border:none;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 70, 961, 581))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffff,\n"
"        stop:0.4 #cbf7ff,\n"
"        stop:1 #a6ecf7\n"
"    );\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/11453740.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "ENTREPREDICT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
