# Form implementation generated from reading ui file 'WELCOME.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(941, 631)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 941, 631))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffff,\n"
"        stop:0.4 #cbf7ff,\n"
"        stop:1 #a6ecf7\n"
"    );\n"
"}")
        self.widget.setObjectName("widget")
        self.mainwidget = QtWidgets.QWidget(parent=self.widget)
        self.mainwidget.setEnabled(True)
        self.mainwidget.setGeometry(QtCore.QRect(0, 0, 941, 631))
        self.mainwidget.setStyleSheet("#label_phrase{\n"
"    font-family: \"Open Sans Light\";\n"
"    font-size: 12pt;\n"
"    font-weight: 300;\n"
"    color: #002B5B;\n"
"    border: none;              /* removes the border completely */\n"
"    background: transparent;   /* ensures no background box */\n"
"}\n"
"")
        self.mainwidget.setObjectName("mainwidget")
        self.label_smalllogo = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_smalllogo.setGeometry(QtCore.QRect(10, 0, 51, 61))
        self.label_smalllogo.setStyleSheet("#label_smalllogo{\n"
"background-color:#031b3d;\n"
"}\n"
"\n"
"#label_smalllogo{\n"
"border-image: url(\"C:/Users/USER/Documents/system_90/nagao_backend/ENTREPREDICT_Icon_Option_1_-_Circuit-Graph_E-removebg-preview.png\");\n"
"}")
        self.label_smalllogo.setText("")
        self.label_smalllogo.setObjectName("label_smalllogo")
        self.label_upperhome = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_upperhome.setGeometry(QtCore.QRect(0, 0, 941, 61))
        self.label_upperhome.setStyleSheet("#label_upperhome{\n"
"background-color:#031b3d;\n"
"}")
        self.label_upperhome.setText("")
        self.label_upperhome.setObjectName("label_upperhome")
        self.plainTextEdit_Entrep = QtWidgets.QPlainTextEdit(parent=self.mainwidget)
        self.plainTextEdit_Entrep.setGeometry(QtCore.QRect(70, 20, 191, 41))
        self.plainTextEdit_Entrep.setStyleSheet("#plainTextEdit_Entrep{\n"
" font-family: \"Montserrat ExtraBold\";\n"
"    font-size: 16pt;\n"
"font-weight: 600;\n"
"color:white;\n"
"background-color:#031b3d;\n"
"border:none;\n"
"}")
        self.plainTextEdit_Entrep.setObjectName("plainTextEdit_Entrep")
        self.frame_sidebar = QtWidgets.QFrame(parent=self.mainwidget)
        self.frame_sidebar.setGeometry(QtCore.QRect(10, 70, 161, 541))
        self.frame_sidebar.setStyleSheet("#frame_sidebar {\n"
"    background-color: #002B5B;\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_sidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_sidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.pushButton_home = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.pushButton_home.setGeometry(QtCore.QRect(40, 30, 91, 31))
        self.pushButton_home.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.pushButton_home.setObjectName("pushButton_home")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 80, 91, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 130, 91, 31))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 230, 91, 31))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: 2px solid #00E5FF;\n"
"    border-radius: 12px;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 480, 91, 31))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #00E5FF;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 6px 18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 229, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 229, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00E5FF;\n"
"    color: #001F3F;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_welcome = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_welcome.setGeometry(QtCore.QRect(210, 100, 271, 41))
        self.label_welcome.setStyleSheet("#label_welcome {\n"
"    color: #00E5FF;\n"
"    font-family: \"Poppins ExtraBold\";\n"
"    font-size: 34pt;\n"
"    font-weight: 800;\n"
"    letter-spacing: 2px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-shadow: 0px 0px 10px rgba(0, 229, 255, 0.6);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.label_welcome.setObjectName("label_welcome")
        self.label_username = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_username.setGeometry(QtCore.QRect(450, 110, 151, 31))
        self.label_username.setStyleSheet("#label_username {\n"
"    color: #00B8D4;  /* deeper cyan-blue for better contrast */\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    font-weight: 500;\n"
"    letter-spacing: 0.5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.label_username.setObjectName("label_username")
        self.label_summary = QtWidgets.QLabel(parent=self.mainwidget)
        self.label_summary.setGeometry(QtCore.QRect(220, 150, 301, 31))
        self.label_summary.setStyleSheet("#label_summary {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #002B5B; /* Black text */\n"
"    background-color: transparent; /* Transparent background */\n"
"}\n"
"")
        self.label_summary.setObjectName("label_summary")
        self.frame_status = QtWidgets.QFrame(parent=self.mainwidget)
        self.frame_status.setGeometry(QtCore.QRect(210, 200, 581, 191))
        self.frame_status.setStyleSheet("#frame_status {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(224, 247, 250, 255),  /* light cyan */\n"
"        stop:1 rgba(255, 255, 255, 255)   /* soft white */\n"
"    );\n"
"    border-radius: 20px;\n"
"    border: 1px solid rgba(0, 188, 212, 60); /* subtle cyan border */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.frame_status.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_status.setObjectName("frame_status")
        self.label_status = QtWidgets.QLabel(parent=self.frame_status)
        self.label_status.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.label_status.setStyleSheet("#label_status{\n"
"    background-color: transparent;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 13pt;\n"
"    font-weight: 600;\n"
"    color: #000000;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.label_status.setObjectName("label_status")
        self.label_predicted = QtWidgets.QLabel(parent=self.frame_status)
        self.label_predicted.setGeometry(QtCore.QRect(40, 40, 491, 51))
        self.label_predicted.setStyleSheet("#label_predicted {\n"
"    font-size: 36pt;      /* Adjust bigger or smaller depending on your layout */\n"
"    font-weight: bold;\n"
"    color: #002B5B;       /* Replace with the exact color of your sidebar frame */\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_predicted.setObjectName("label_predicted")
        self.label_confidence = QtWidgets.QLabel(parent=self.frame_status)
        self.label_confidence.setGeometry(QtCore.QRect(50, 100, 271, 31))
        self.label_confidence.setStyleSheet("#label_confidence {\n"
"    font-size: 15pt;      /* Smaller than 36pt of PREDICTED SUCCESS */\n"
"    font-weight: semi-bold;\n"
"    color: #002B5B;       /* Same as sidebar / PREDICTED SUCCESS for consistency */\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_confidence.setObjectName("label_confidence")
        self.label_last = QtWidgets.QLabel(parent=self.frame_status)
        self.label_last.setGeometry(QtCore.QRect(50, 140, 231, 21))
        self.label_last.setStyleSheet("#label_last {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #002B5B; /* Black text */\n"
"    background-color: transparent; /* Transparent background */\n"
"}\n"
"")
        self.label_last.setObjectName("label_last")
        self.frame_tips = QtWidgets.QFrame(parent=self.mainwidget)
        self.frame_tips.setGeometry(QtCore.QRect(210, 400, 301, 191))
        self.frame_tips.setStyleSheet("#frame_tips {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(224, 247, 250, 255),  /* light cyan */\n"
"        stop:1 rgba(255, 255, 255, 255)   /* soft white */\n"
"    );\n"
"    border-radius: 20px;\n"
"    border: 1px solid rgba(0, 188, 212, 60); /* subtle cyan border */\n"
"    padding: 15px;\n"
"}\n"
"")
        self.frame_tips.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tips.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tips.setObjectName("frame_tips")
        self.label_tips = QtWidgets.QLabel(parent=self.frame_tips)
        self.label_tips.setGeometry(QtCore.QRect(8, 19, 191, 31))
        self.label_tips.setStyleSheet("#label_tips{\n"
"    background-color: transparent;\n"
"    font-family: \"Poppins\";\n"
"    font-size: 13pt;\n"
"    font-weight: 600;\n"
"    color: #000000;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.label_tips.setObjectName("label_tips")
        self.label_bullet = QtWidgets.QLabel(parent=self.frame_tips)
        self.label_bullet.setGeometry(QtCore.QRect(20, 60, 261, 71))
        self.label_bullet.setStyleSheet("#label_bullet{\n"
"    font-size: 11pt;          /* Similar to summary/last update */\n"
"    font-weight: normal;       /* Keep it readable */\n"
"    color: #001F3F;            /* Consistent text color */\n"
"    background: transparent;\n"
"    border: none;              /* No border */\n"
"}\n"
"")
        self.label_bullet.setObjectName("label_bullet")
        self.label_upperhome.raise_()
        self.label_smalllogo.raise_()
        self.plainTextEdit_Entrep.raise_()
        self.frame_sidebar.raise_()
        self.label_welcome.raise_()
        self.label_username.raise_()
        self.label_summary.raise_()
        self.frame_status.raise_()
        self.frame_tips.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plainTextEdit_Entrep.setPlainText(_translate("Form", "ENTREPREDICT"))
        self.pushButton_home.setText(_translate("Form", "Home"))
        self.pushButton_2.setText(_translate("Form", "Inventory"))
        self.pushButton_3.setText(_translate("Form", "Sales"))
        self.pushButton_4.setText(_translate("Form", "Prediction"))
        self.pushButton_5.setText(_translate("Form", "Income"))
        self.pushButton_6.setText(_translate("Form", "Log Out"))
        self.label_welcome.setText(_translate("Form", "Welcome!"))
        self.label_username.setText(_translate("Form", "[USERNAME]"))
        self.label_summary.setText(_translate("Form", "Here\'s your business summary."))
        self.label_status.setText(_translate("Form", "Business Status"))
        self.label_predicted.setText(_translate("Form", "PREDICTED SUCCESS!"))
        self.label_confidence.setText(_translate("Form", "Confidence Level: 87%"))
        self.label_last.setText(_translate("Form", "Last Prediction update  10/09/25"))
        self.label_tips.setText(_translate("Form", "Tips for Improvement "))
        self.label_bullet.setText(_translate("Form", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Maintain sales growth</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Reduce slow-moving inventory</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Monitor next month\'s expenses</li></ul></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
